### ISSUE TITLE
Double namespaced

### ISSUE THREAD

**Issue by arixrobotics** [moose-cpr/moose#4]
https://github.com/moose-cpr/moose/blob/de3d01768cc5db103df9395bff9ffb3d6f7347e4/moose_control/config/teleop.yaml#L1

With this line no 1, the params become as below, having the namespace '''/joy_teleop''' twice. 
> /joy_teleop/joy_teleop/joy_node/autorepeat_rate
> /joy_teleop/joy_teleop/joy_node/deadzone
> /joy_teleop/joy_teleop/teleop_twist_joy/axis_angular
> /joy_teleop/joy_teleop/teleop_twist_joy/axis_linear
> /joy_teleop/joy_teleop/teleop_twist_joy/enable_button
> /joy_teleop/joy_teleop/teleop_twist_joy/enable_turbo_button
> /joy_teleop/joy_teleop/teleop_twist_joy/scale_angular
> /joy_teleop/joy_teleop/teleop_twist_joy/scale_linear
> /joy_teleop/joy_teleop/teleop_twist_joy/scale_linear_turbo
 
This caused the teleop not to work as expected. Suggest to simply remove this line no 1.

**Comment by civerachb-cpr** [comment]
Thanks for letting us know! I've submitted a PR to address this issue.
